version: '3.8'
services:
  we-bot-whatsapp:
    image: node-whatsapp-web:2.0
    volumes:
      - ./src:/app/src
      - ./media:/app/media
      - ./index.js:/app/index.js
    environment:
      - NODE_ENV=production
    ports:
      - "9000:9000"