name: Deploy to Production VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy multiple bots to VPS (separate folders)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            BASE_DIR="$HOME"
            REPO_URL="https://github.com/1608-EQUIPOSISTEMAS/BOTENVIVO.git"

            declare -A projects=(
              ["arleth"]=3050
              ["camilo"]=3053
              ["isabel"]=3054
              ["fabiana"]=3055
            )

            echo ">>> Iniciando despliegue por carpetas..."

            for project in "${!projects[@]}"; do
              FOLDER="${BASE_DIR}/BOTENVIVO-${project}"
              PORT=${projects[$project]}

              echo "-----------------------------------------"
              echo ">>> Desplegando ${project} en ${FOLDER} (puerto ${PORT})"

              # 1. Clonar o actualizar cada carpeta
              if [ -d "$FOLDER" ]; then
                echo ">>> Actualizando repo existente en $FOLDER"
                cd "$FOLDER"
                git reset --hard
                git pull origin master
              else
                echo ">>> Clonando nueva copia del repo..."
                git clone -b master "$REPO_URL" "$FOLDER"
                cd "$FOLDER"
              fi

              # 2. Eliminar sesiones/caché de WhatsApp
              echo ">>> Eliminando sesiones anteriores de WhatsApp..."
              rm -rf .wwebjs_auth .wwebjs_cache .wwebjs .session session.json auth/ WWebJS/ sessions/ temp/ cache/ || true

              # 3. Instalar dependencias
              echo ">>> Instalando dependencias..."
              npm install --omit=dev

              # 4. Iniciar/reiniciar con PM2
              echo ">>> Iniciando servicio PM2..."
              PORT=$PORT pm2 restart $project || PORT=$PORT pm2 start index.js --name $project --cwd "$FOLDER"

            done

            # 5. Guardar configuración de PM2
            pm2 save

            echo "✅ Despliegue finalizado correctamente."
