name: Deploy to Production VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy multiple bots to VPS (separate folders)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            BASE_DIR="$HOME"
            REPO_URL="https://github.com/1608-EQUIPOSISTEMAS/BOTENVIVO.git"

            declare -A projects=(
              ["alexis1"]=3050
              ["alexis2"]=3051
              ["alexis3"]=3052
              ["alexis4"]=3053
              ["alexis5"]=3054
              ["alexis6"]=3055
            )

            echo ">>> Iniciando despliegue por carpetas..."

            for project in "${!projects[@]}"; do
              FOLDER="${BASE_DIR}/BOTENVIVO-${project}"
              PORT=${projects[$project]}

              echo "-----------------------------------------"
              echo ">>> Desplegando ${project} en ${FOLDER} (puerto ${PORT})"

              # 1. Clonar o actualizar cada carpeta
              if [ -d "$FOLDER" ]; then
                echo ">>> Actualizando repo existente en $FOLDER"
                cd "$FOLDER"
                git pull origin master
              else
                echo ">>> Clonando nueva copia del repo..."
                git clone -b master "$REPO_URL" "$FOLDER"
                cd "$FOLDER"
              fi

              # 2. Instalar dependencias
              echo ">>> Instalando dependencias..."
              npm install --omit=dev

              # 3. Iniciar/reiniciar con PM2
              echo ">>> Iniciando servicio PM2..."
              PORT=$PORT pm2 restart $project || PORT=$PORT pm2 start index.js --name $project --cwd "$FOLDER"

            done

            # 4. Guardar configuración de PM2
            pm2 save

            echo "✅ Despliegue finalizado correctamente."

